var alph26="ABCDEFGHIJKLMNOPQRSTUVWXYZ",alph36="A1B2C3D4E5F6G7H8I9J0KLMNOPQRSTUVWXYZ",alphabet,keyedAlph,keyedAlph2,keyedAlph3,missGrdLtr="J",replGrdLtr="I",gridWd,gridSz,cType;function disp(a){a=document.createTextNode(a+"\n");document.getElementById("x").appendChild(a)}function ord(a){return a.charCodeAt(0)}function chr(a){return String.fromCharCode(a)}function getRadioVal(a,c){var b,d=a.elements[c],e=d.length;for(b=0;b<e;b+=1)if(!0===d[b].checked){var f=d[b].value;break}return f}
function formatCipher(a,c,b,d,e,f){if(0===b.length)return"";a=getRadioVal(document.forms[a],c);if(f)switch(a){case "showGp":b=b.toUpperCase().replace(/[^0-9]/ig,"").replace(/(\w{5})/g,"$1 ").replace(/(^\s+|\s+$)/,"");break;case "showOrig":break;case "showCphr":b=b.toUpperCase().replace(/[^0-9]/ig,"");break;case "showPair":b=b.toUpperCase().replace(/[^0-9]/ig,"").replace(/(\w{2})/g,"$1 ").replace(/(^\s+|\s+$)/,"");break;default:e=new RegExp("(\\w{"+e+"})","g"),b=b.toUpperCase().replace(/[^0-9]/ig,
""),b=b.toUpperCase().replace(e,"$1 ").trim()}else if(0<d.length)switch(d=new RegExp("[^"+alphabet+"]","g"),a){case "showGp":b=b.toUpperCase().replace(d,"").replace(/(\S{5})/g,"$1 ").replace(/(^\s+|\s+$)/,"");break;case "showOrig":break;case "showCphr":b=b.toUpperCase().replace(d,"");break;case "showPair":b=b.toUpperCase().replace(d,"").replace(/(\w{2})/g,"$1 ").replace(/(^\s+|\s+$)/,"");break;default:e=new RegExp("(\\S{"+e+"})","g"),b=b.toUpperCase().replace(d,""),b=b.toUpperCase().replace(e,"$1 ").trim()}else if(36!==
alphabet.length)switch(a){case "showGp":b=b.toUpperCase().replace(/[^a-zA-Z]/ig,"").replace(/(\w{5})/g,"$1 ").replace(/(^\s+|\s+$)/,"");break;case "showOrig":break;case "showCphr":b=b.toUpperCase().replace(/[^a-zA-Z]/ig,"");break;case "showPair":b=b.toUpperCase().replace(/[^a-zA-Z]/ig,"").replace(/(\w{2})/g,"$1 ").replace(/(^\s+|\s+$)/,"");break;default:e=new RegExp("(\\w{"+e+"})","g"),b=b.toUpperCase().replace(/[^a-zA-Z]/ig,""),b=b.toUpperCase().replace(e,"$1 ").trim()}else switch(a){case "showGp":b=
b.toUpperCase().replace(/[^a-zA-Z0-9]/ig,"").replace(/(\w{5})/g,"$1 ").replace(/(^\s+|\s+$)/,"");break;case "showOrig":break;case "showCphr":b=b.toUpperCase().replace(/[^a-zA-Z0-9]/ig,"");break;case "showPair":b=b.toUpperCase().replace(/[^a-zA-Z0-9]/ig,"").replace(/(\w{2})/g,"$1 ").replace(/(^\s+|\s+$)/,"");break;default:e=new RegExp("(\\w{"+e+"})","g"),b=b.toUpperCase().replace(/[^a-zA-Z0-9]/ig,""),b=b.toUpperCase().replace(e,"$1 ").trim()}return b}
function grpGrdSzChanged(a){gridWd=Number(getRadioVal(document.forms[a],"alphSz"));gridSz=gridWd*gridWd;routes=genRoutes();showKySqr()}
function showKySqr(){var a;alphabet=5===gridWd?alph26.replace(new RegExp(missGrdLtr,"g"),""):alph36;if(document.getElementById("keywdID").value){if(5===gridWd)var c=document.getElementById("keywdID").value.toUpperCase().replace(/[^A-Z]/g,"").replace(new RegExp(missGrdLtr,"g"),replGrdLtr);else for(c=document.getElementById("keywdID").value.toUpperCase().replace(/[^A-Z0-9]/g,""),a=0;a<c.length;a+=1){var b=c.charAt(a);"J"===b&&0!==c.indexOf("0")&&(c=c.slice(0,a+1)+"0"+c.slice(a+1));"A"<=b&&"I">=b&&0!==
c.indexOf(chr(ord(b)-16))&&(c=c.slice(0,a+1)+chr(ord(b)-16)+c.slice(a+1))}c+=alphabet;for(a=0;a<c.length;a+=1)for(;0<=c.indexOf(c[a],a+1);)c=c.slice(0,c.lastIndexOf(c[a]))+c.slice(c.lastIndexOf(c[a])+1)}else c=alphabet;if(document.getElementById("keywdID2"))if(document.getElementById("keywdID2").value){if(5===gridWd)var d=document.getElementById("keywdID2").value.toUpperCase().replace(/[^A-Z]/g,"").replace(new RegExp(missGrdLtr,"g"),replGrdLtr);else for(d=document.getElementById("keywdID2").value.toUpperCase().replace(/[^A-Z0-9]/g,
""),a=0;a<d.length;a+=1)b=d.charAt(a),"J"===b&&0!==d.indexOf("0")&&(d=d.slice(0,a+1)+"0"+d.slice(a+1)),"A"<=b&&"I">=b&&0!==d.indexOf(chr(ord(b)-16))&&(d=d.slice(0,a+1)+chr(ord(b)-16)+d.slice(a+1));d+=alphabet;for(a=0;a<d.length;a+=1)for(;0<=d.indexOf(d[a],a+1);)d=d.slice(0,d.lastIndexOf(d[a]))+d.slice(d.lastIndexOf(d[a])+1)}else d=alphabet;if(document.getElementById("keywdID3"))if(document.getElementById("keywdID3").value){if(5===gridWd)var e=document.getElementById("keywdID3").value.toUpperCase().replace(/[^A-Z]/g,
"").replace(new RegExp(missGrdLtr,"g"),replGrdLtr);else for(e=document.getElementById("keywdID3").value.toUpperCase().replace(/[^A-Z0-9]/g,""),a=0;a<e.length;a+=1)b=e.charAt(a),"J"===b&&0!==e.indexOf("0")&&(e=e.slice(0,a+1)+"0"+e.slice(a+1)),"A"<=b&&"I">=b&&0!==e.indexOf(chr(ord(b)-16))&&(e=e.slice(0,a+1)+chr(ord(b)-16)+e.slice(a+1));e+=alphabet;for(a=0;a<e.length;a+=1)for(;0<=e.indexOf(e[a],a+1);)e=e.slice(0,e.lastIndexOf(e[a]))+e.slice(e.lastIndexOf(e[a])+1)}else e=alphabet;a=document.getElementById("selectRoute").selectedIndex;
keyedAlph=kyToRt(c,a);c=keyedAlph.replace(/(\w)/g,"$1 ");c=5===gridWd?c.replace(/(.{10})/g,"$1\n"):c.replace(/(.{12})/g,"$1\n");document.getElementById("kySqr").value=c;document.getElementById("selectRoute2")&&(a=document.getElementById("selectRoute2").selectedIndex,keyedAlph2=kyToRt(d,a),c=keyedAlph2.replace(/(\w)/g,"$1 "),c=5===gridWd?c.replace(/(.{10})/g,"$1\n"):c.replace(/(.{12})/g,"$1\n"),document.getElementById("kySqr2").value=c);document.getElementById("selectRoute3")&&(a=document.getElementById("selectRoute3").selectedIndex,
keyedAlph3=kyToRt(e,a),c=keyedAlph3.replace(/(\w)/g,"$1 "),c=5===gridWd?c.replace(/(.{10})/g,"$1\n"):c.replace(/(.{12})/g,"$1\n"),document.getElementById("kySqr3").value=c)}function ShowHide(a,c){document.getElementById(a).checked?document.getElementById(c).style.display="block":document.getElementById(c).style.display="none"}
function rot(a,c){switch(cType){case 0:return chr((26+ord(a)+ord(c)-2*ord("A"))%26+ord("A"));case 1:return chr((26+ord(c)-ord(a))%26+ord("A"));case 2:return chr((26+ord(a)-ord(c))%26+ord("A"));default:var b=Math.floor((ord(c)-ord("A"))/2)+13;if(ord(a)>ord("M"))return ord(a)-b<ord("A")?chr(ord(a)-b+13):chr(ord(a)-b)}return ord(a)+b>ord("Z")?chr(ord(a)+b-13):chr(ord(a)+b)}
function getCiphName(a){switch(a){case 0:return"Vigen\u00e8re";case 1:return"Beaufort";case 2:return"Variant";default:return"Porta"}}function getCoords(a,c){return{r:Math.floor(a.indexOf(c)/gridWd),c:a.indexOf(c)%gridWd}}
function getKeyedAlph(a,c){var b;var d=!0===c?document.getElementById("keywdID").value.toUpperCase().replace(/[^A-Z]/g,"").replace(new RegExp(missGrdLtr,"g"),replGrdLtr):0<a.length?a.toUpperCase().replace(/[^A-Z]/g,"")+alph26:document.getElementById("keywdID").value.toUpperCase().replace(/[^A-Z]/g,"")+alph26;for(b=0;b<d.length;b+=1)for(;0<=d.indexOf(d[b],b+1);)d=d.slice(0,d.lastIndexOf(d[b]))+d.slice(d.lastIndexOf(d[b])+1);return d}
function validateKeypress(a,c){a=a||window.event;var b=a.keyCode||a.which;if(8===b||46===b||37===b||39===b||a.ctrlKey&&86===b||a.ctrlKey&&67===b||a.ctrlKey&&99===b||a.ctrlKey&&118===b)return!0;b=String.fromCharCode(b);switch(c){case 0:return/[A-Za-z]/i.test(b);case 1:return/[0-9]/i.test(b);case 2:return/[A-Za-z0-9]/i.test(b);case 3:return/[A-Ja-j0-9]/i.test(b);case 4:return/[A-Za-z#]/i.test(b);case 5:return/[0-9,\s]/i.test(b)}}
function cnvrtTxtToUniqNumOrdr(a){var c,b,d=[];for(c=0;c<a.length;c+=1)d[c]="";var e=-1;for(c=ord("0");c<=ord("Z");c+=1)for(b=a.indexOf(chr(c));-1<b;)e+=1,d[b]=e,b=a.indexOf(chr(c),b+1);return d}function cnvrtTxtToNumOrdr(a){var c,b=[];for(c=0;c<a.length;c+=1)b[c]="";var d=-1;for(c=ord("0");c<=ord("Z");c+=1){var e=a.indexOf(chr(c));for(-1<e&&(d+=1);-1<e;)b[e]=d,e=a.indexOf(chr(c),e+1)}return b}
function getAlphabet(a){switch(a){case "0":a="ABCDEFGHIKLMNOPQRSTUVWXYZ";break;case "1":a="ABCDEFGHIJKLMNOPQRSTUVWXYZ";break;case "2":a="ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789";break;default:a="-ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789.,;:?!'\""}return a};