var uInt8Array,singleScores=[],englishAlph="ABCDEFGHIJKLMNOPQRSTUVWXYZ",englishAlphNum="A1B2C3D4E5F6G7H8I9J0KLMNOPQRSTUVWXYZ";
function readTetragraph(a,b){var c=new XMLHttpRequest;"withCredentials"in c?(c.open("GET",a,!0),c.responseType="arraybuffer",c.onload=function(d){4!==c.readyState||200!==c.status&&0!==c.status||(uInt8Array=new Uint8Array(c.response),document.getElementById("warning").value=b+" data file loaded")},c.send()):"undefined"!==typeof XDomainRequest?(c=new XDomainRequest,c.open("GET",a)):c=null}
function readDatafile(){var a=document.getElementById("accent")&&!0===document.getElementById("accent").checked?!0:!1;var b=document.getElementById("langID").value;switch(b){case "English":a="../language/engTetra.dat";break;case "Afrikaans":a="../language/afrTetra.dat";break;case "Catalan":a="../language/catTetra.dat";break;case "Danish":a=!0===a?"../language/danTetraX.dat":"../language/danTetra.dat";break;case "Dutch":a="../language/dutTetra.dat";break;case "Esperanto":a="../language/espTetra.dat";
break;case "French":a="../language/freTetra.dat";break;case "German":a=!0===a?"../language/gerTetraX.dat":"../language/gerTetra.dat";break;case "Italian":a="../language/itaTetra.dat";break;case "Latin":a="../language/latTetra.dat";break;case "Norwegian":a=!0===a?"../language/norTetraX.dat":"../language/norTetra.dat";break;case "Polish":a="../language/polTetra.dat";break;case "Portuguese":a="../language/porTetra.dat";break;case "Spanish":a=!0===a?"../language/spaTetraX.dat":"../language/spaTetra.dat";
break;case "Swedish":a=!0===a?"../language/sweTetraX.dat":"../language/sweTetra.dat";break;default:a="../language/engTetra.dat"}readTetragraph(a,b)}
function readSingles(a){var b,c,d,e=new XMLHttpRequest;a="../language/engSingles.txt";"withCredentials"in e?(e.open("GET",a,!0),e.responseType="text",e.onload=function(f){if(4===e.readyState&&(200===e.status||0===e.status))for(c=e.responseText,d=c.split("\n"),b=0;b<d.length;b+=1)singleScores[b]=0<d[b]?10*Math.log10(d[b]):0},e.send()):"undefined"!==typeof XDomainRequest?(e=new XDomainRequest,e.open("GET",a)):e=null}
function readSinglesData(){switch(document.getElementById("langID").value.substring(0,3)){case "Eng":var a="../language/engTetra.dat";break;case "Afr":a="../language/afrTetra.dat";break;case "Cat":a="../language/catTetra.dat";break;case "Dan":a="../language/danTetra.dat";break;case "Dut":a="../language/dutTetra.dat";break;case "Esp":a="../language/espTetra.dat";break;case "Fre":a="../language/freTetra.dat";break;case "Ger":a="../language/gerTetra.dat";break;case "Ita":a="../language/itaTetra.dat";
break;case "Lat":a="../language/latTetra.dat";break;case "Nor":a="../language/norTetra.dat";break;case "Pol":a="../language/polTetra.dat";break;case "Por":a="../language/porTetra.dat";break;case "Spa":a="../language/spaTetra.dat";break;case "Swe":a="../language/sweTetra.dat";break;default:a="../language/engTetra.dat"}readSingles(a)}
function periodChanged(a){var b=parseInt(document.getElementById("minPerd").value),c=parseInt(document.getElementById("maxPerd").value);0===a?c<b&&(document.getElementById("maxPerd").value=b):c<b&&(document.getElementById("minPerd").value=c)}function sortFunction(a,b){return a[0]===b[0]?0:a[0]<b[0]?1:-1}function getPerdCiphName(a){switch(a){case 0:return"Vigen\u00e8re";case 1:return"Beaufort";case 2:return"Variant Beaufort";case 3:return"Porta"}return"Gronsfeld"}
function typeChanged(a){a=Number(getRadioVal(document.forms.frm,"ciphTyp"));document.getElementById("header").innerHTML=getCiphName(a)+" Cipher"}function cleanInput(a,b){if("undefined"===typeof a)return"";a=a.toUpperCase();switch(b){case 0:var c=a.replace(/[^A-Z]/g,"");break;case 1:c=a.replace(/[^0-9]/g,"");break;case 2:c=a.replace(/[^A-Z0-9]/g,"");break;case 3:c=a.replace(/[^A-J0-9]/g,"");break;case 4:c=a.replace(/[^A-Z#]/g,"");break;case 5:c=a.replace(/[^0-9.\s]/g,"")}return c}
function readLanguages(){return"English Afrikaans Catalan Danish Dutch Esperanto French German Italian Latin Norwegian Polish Portuguese Spanish Swedish".split(" ")}function readLangMenu(){var a,b=document.getElementById("langID"),c=readLanguages();for(a=0;a<c.length;a+=1){var d=c[a];var e=document.createElement("option");e.textContent=d;e.value=d;b.appendChild(e)}}
function readWorkersMenu(){var a=document.getElementById("workerCount"),b=[];window.opr&&opr.addons||window.opera||navigator.userAgent.indexOf(" OPR/");/constructor/i.test(window.HTMLElement);var c=!!document.documentMode;var d=navigator.hardwareConcurrency||4;!c&&window.StyleMedia||c||(d-=2);1>d&&(d=1);for(c=0;c<d;c+=1)b[c]=c+1;for(c=0;c<b.length;c+=1){d=b[c];var e=document.createElement("option");e.textContent=d;e.value=d;a.appendChild(e)}}
function readMissingLetterMenu(){var a,b=document.getElementById("missingLtr"),c=[];for(a=0;a<englishAlph.length;a+=1)c[a]=englishAlph.charAt(a);for(a=0;a<c.length;a+=1){var d=c[a];var e=document.createElement("option");e.textContent=d;"J"===d&&(e.selected=!0);e.value=d;b.appendChild(e)}}function readAlphabets(){return["ABCDEFGHIJKLMNOPQRSTUVWXYZ","ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789","ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789.,:';?!-\""]}
function readLangAlphabets(){var a="undefined"===typeof a?"ABCDEFGHIJKLMNOPQRSTUVWXYZ":alph26;if(!0===document.getElementById("accent").checked){switch(document.getElementById("langID").value){case "Danish":a+="\u00c6\u00d8\u00c5";break;case "German":a+="\u00c4\u00d6\u00dc";break;case "Norwegian":a+="\u00c6\u00d8\u00c5";break;case "Swedish":a+="\u00c5\u00c4\u00d6"}26<a.length&&(a=a.replace("Q",""),a=a.replace("W",""),a=a.replace("Z",""))}return a}
function readAlphbtMenu(){var a,b=document.getElementById("alphID"),c=readAlphabets();for(a=0;a<c.length;a+=1){var d=c[a];var e=document.createElement("option");e.textContent=d;e.value=d;b.appendChild(e)}}function convertToLetters(a){var b,c="";a=a.toUpperCase();for(b=0;b<a.length;b+=1)if(isNumeric(a[b])){var d=chr(ord(a[b])-ord("1")+ord("A"));c+=d}else c+=a[b];return c}
function convertToNumbers(a){var b,c="";a=a.toUpperCase();for(b=0;b<a.length;b+=1)if(isNumeric(a[b])){var d=chr(ord(a[b])-ord("1")+ord("A"));c+=d}else c+=a[b];return c}function isKeywordRepeated(a){var b,c=!0;for(b=0;b<a.length;b+=1)0<"".indexOf(""[b],b+1)&&(c=!1);return c}function isKeywordComplete(a){var b,c=!0;for(b=0;b<a.length;b+=1)isNumeric(a[b])&&chr(ord(a[b])-ord("1")+ord("A"));for(b=0;b<a.length;b+=1)-1===a.indexOf(chr(ord("A")+b))&&(c=!1);return c}
function isNumeric(a){return!isNaN(parseFloat(a))&&isFinite(a)}function getFactorial(a){function b(d){return 0===d||1===d?1:0<c[d]?c[d]:c[d]=b(d-1)*d}var c=[];return b(a)}function initSolution(){var a,b;for(a=0;a<=maxSol;a+=1)for(solutions[a]=[3],b=0;3>b;b+=1)solutions[a][b]=0}function initSolutionFour(){var a,b;for(a=0;a<=maxSol;a+=1)for(solutions[a]=[4],b=0;4>b;b+=1)solutions[a][b]=0};