var plain,cipher,keyNumber,numSols,uInt8Array,workerNumber,totalWorkers,alphabet,routes,isRunning,units,tens,teens,hundred,thousand,and,plainAlph,solutions=[],gridSize;
function decipherBazeries(){"function"===typeof importScripts&&(importScripts("../support/decipherLib.js"),importScripts("../support/cryptoPrograms.js"));gridSize=Math.floor(Math.sqrt(alphabet.length));initSolution();readNumberText();plainAlph=reorderAlph();"undefined"!==typeof keyNumber&&(0<keyNumber.length?solveWithKeyword():solveBazeries());!1===isRunning&&self.postMessage({cmd:"STOP",msg:""})}
function solveBazeries(){var a=workerNumber;isRunning=!0;var b=0;a:for(;1>=b;b+=1)for(keyNumber=a+1;999999>=keyNumber;keyNumber+=totalWorkers)if(isRunning){var c=convertKeyToText(keyNumber,b);if(5===gridSize)var f=getKeyedAlphabet(alphabet,c);else{f=getKeyedAlphabet(englishAlph36,c);var g=getACAKeyedAlphabet(alphabet,c)}for(c=0;c<routes.length;c+=1){var d="";for(b=0;b<alphabet.length;b+=1)d+=f[routes[c][b]];var e=5===gridSize?decrypt(d):decrypt6x6(d);plain=reverseText(e);e=5===gridSize?getTetraScore(plain):
getTetraScore(plain.replace(/[^a-z]/g,""));solutions[numSols-1]<e&&(solutions[numSols-1]=e,solutions.sort(function(h,k){return k-h}),self.postMessage({cmd:"reslt",key:d+"\u00a0("+keyNumber.toString()+")",score:e,text:plain}));if(6===gridSize){d="";for(b=0;b<alphabet.length;b+=1)d+=g[routes[c][b]];e=decrypt6x6(d);plain=reverseText(e);e=getTetraScore(plain.replace(/[^a-z]/g,""));solutions[numSols-1]<e&&(solutions[numSols-1]=e,solutions.sort(function(h,k){return k-h}),self.postMessage({cmd:"reslt",key:d+
"\u00a0("+keyNumber.toString()+")",score:e,text:plain}))}}}else break a;isRunning=!1}
function solveWithKeyword(){var a;if(0<keyNumber&&999999>=keyNumber)for(a=0;1>=a;a+=1){var b=convertKeyToText(keyNumber,a);if(5===gridSize)var c=getKeyedAlphabet(alphabet,b);else{c=getKeyedAlphabet(englishAlph36,b);var f=getACAKeyedAlphabet(alphabet,b)}isRunning=!0;for(b=0;b<routes.length;b+=1){var g="";for(a=0;a<alphabet.length;a+=1)g+=c[routes[b][a]];var d=decrypt(g);plain=reverseText(d);d=5===gridSize?getTetraScore(plain):getTetraScore(plain.replace(/[^a-z]/g,""));solutions[numSols-1]<d&&(solutions[numSols-
1]=d,solutions.sort(function(e,h){return h-e}),self.postMessage({cmd:"reslt",key:g+"\u00a0("+keyNumber.toString()+")",score:d,text:plain}));if(6===gridSize){g="";for(a=0;a<alphabet.length;a+=1)g+=f[routes[b][a]];d=decrypt6x6(g);plain=reverseText(d);d=getTetraScore(plain.replace(/[^a-z]/g,""));solutions[numSols-1]<d&&(solutions[numSols-1]=d,solutions.sort(function(e,h){return h-e}),self.postMessage({cmd:"reslt",key:g+"\u00a0("+keyNumber.toString()+")",score:d,text:plain}))}}}isRunning=!1}
function decrypt(a){var b;var c=cipher;var f=plainAlph.toLowerCase();for(b=0;b<a.length;b+=1)c=c.replaceAll(a.charAt(b),f.substr(b,1));return c}function decrypt6x6(a){var b,c="";for(b=0;b<cipher.length;b+=1)c+=plainAlph.substr(a.indexOf(cipher.charAt(b)),1);return c.toLowerCase()}String.prototype.replaceAll=function(a,b){return this.replace(new RegExp(a,"g"),b)};
function reverseText(a){var b,c;var f=keyNumber.toString();var g=c=0;var d="";do{var e=parseInt(f[g]);var h=a.substr(c,e);for(b=h.length-1;0<=b;--b)d+=h.charAt(b);c+=e;g=(g+1)%f.length}while(c<a.length);return d}function reorderAlph(){var a,b,c,f=[];for(c=a=0;c<gridSize;c+=1)for(b=0;b<gridSize*gridSize;b+=gridSize)f[a]=alphabet[b+c],a+=1;return f.join("")}
function readNumberText(){units=" ONE TWO THRE FOUR FIVE SIX SEVN EIGHT NIE".split(" ");teens="TEN ELVN TWELV THIREN FOURTEN FITEN SIXTEN SEVNT EIGHTN NIET".split(" ");tens="  TWENY THIRY FORTY FITY SIXTY SEVNTY EIGHTY NIETY".split(" ");hundred="HUNDRE";thousand="THOUSAND";and="AND"}
function convertKeyToText(a,b){var c="";var f=keyNumber;1E5<=a&&(c+=addUnits(Math.floor(a/1E5)),c+=hundred,a%=1E5,1E3<=a&&1===b&&(c+=and),1E3>a&&(c+=thousand));1E3<=a&&(c+=addUnits(Math.floor(a/1E3)),c+=thousand);a%=1E3;100<=a&&(c+=addUnits(Math.floor(a/100)),c+=hundred);a%=100;0<a&&100<f&&1===b&&(c+=and);return c+=addUnits(a)}function addUnits(a){var b="";10<=a&&19>=a?b+=teens[a-10]:(19<=a&&(b+=tens[Math.floor(a/10)]),a%=10,0<a&&(b+=units[a]));return b}
self.addEventListener("message",function(a){a=a.data;cipher=a.cipher;uInt8Array=a.uInt8Array;totalWorkers=a.totalWorkers;workerNumber=a.workerNumber;numSols=a.numSols;alphabet=a.alphabet;keyNumber=a.keyword;routes=a.routes;decipherBazeries()},!1);