var plain,period,solutions=[],cipher,keyword,minPeriod,maxPeriod,numSols,uInt8Array,workerNumber,totalWorkers,alphabet,routes,isRunning,cipherTopRow,cipherBottomRow,topIndRow,bottomIndRow;function decipherBifid(){"function"===typeof importScripts&&(importScripts("../support/decipherLib.js"),importScripts("../support/cryptoPrograms.js"));initSolution();"undefined"!==typeof keyword&&(0<keyword.length?solveWithKeyword():solveBifid());!1===isRunning&&self.postMessage({cmd:"STOP",msg:""})}
function solveBifid(){var b,a,g;var c=[];var e=[],d=[],m=[];var l=alphabet.length;var f=Math.sqrt(alphabet.length);var n=0;var p=minPeriod===maxPeriod?minPeriod:minPeriod+workerNumber;isRunning=!0;period=p;a:for(;period<=maxPeriod;period+=totalWorkers)for(createCoordinates(period),rearrangeCipher(period),p=0;1E3>p;p+=1)if(isRunning){c=randomiseAlphabet(l,alphabet).split("");for(b=0;b<c.length;b+=1)d[b]=c[b],e[b]=c[b];plain=decrypt(d.join(""),f);b=5===f?getTetraScore(plain):getTetraScore(plain.replace(/[^a-z]/g,
""));b>n&&(n=b);solutions[numSols-1]<b&&(solutions[numSols-1]=b,solutions.sort(function(r,t){return t-r}),self.postMessage({cmd:"reslt",key:d.join(""),score:b,text:plain}));for(g=15;1<g;--g)if(isRunning){var q=c=0;do{var h=Math.floor(50*Math.random());switch(h){case 1:case 2:case 8:for(a=0;a<l;a+=1)d[a]=e[routes[h][a]];break;case 3:for(a=0;a<l;a+=1)d[a]=e[a];h=Math.floor(Math.random()*f)*f;var k=Math.floor(Math.random()*f)*f;for(a=0;a<f;a+=1)m[a]=d[h+a];for(a=0;a<f;a+=1)d[h+a]=d[k+a];for(a=0;a<f;a+=
1)d[k+a]=m[a];break;case 4:for(a=0;a<l;a+=1)d[a]=e[a];h=Math.floor(Math.random()*f);k=Math.floor(Math.random()*f);for(a=0;a<f;a+=1)m[a]=d[h+a*f];for(a=0;a<f;a+=1)d[h+a*f]=d[k+a*f];for(a=0;a<f;a+=1)d[k+a*f]=m[a];break;default:for(a=0;a<l;a+=1)d[a]=e[a];a=Math.floor(Math.random()*l);h=Math.floor(Math.random()*l);k=d[a];d[a]=d[h];d[h]=k}plain=decrypt(d.join(""),f);a=5===f?getTetraScore(plain):getTetraScore(plain.replace(/[^a-z]/g,""));a>q&&(q=a,q>n&&(n=q));solutions[numSols-1]<a&&(solutions[numSols-
1]=a,solutions.sort(function(r,t){return t-r}),self.postMessage({cmd:"reslt",key:d.join(""),score:a,text:plain}));k=a-b;h=0;if(0<k)h=1;else{k=Math.pow(Math.E,k/g);var u=(1E3*Math.random()+1)/1E3;k>u&&(h=1)}if(1===h){for(b=0;b<d.length;b+=1)e[b]=d[b];b=a}c+=1}while(1E3>c&&isRunning)}else break a}else break a;isRunning=!1}
function createCoordinates(b){var a;var g=Math.floor(cipher.length/b);var c=cipher.length%b;bottomIndRow=topIndRow="";for(a=0;a<g;a+=1)topIndRow+="rcrcrcrcrcrcrcrcrcrc".substr(0,b);topIndRow+="rcrcrcrcrcrcrcrcrcrc".substr(0,c);if(1===b%2)for(a=0;a<g;a+=1)bottomIndRow+="rcrcrcrcrcrcrcrcrcrc".substr(1,b);else for(a=0;a<g;a+=1)bottomIndRow+="rcrcrcrcrcrcrcrcrcrc".substr(0,b);0<c&&(bottomIndRow=1===c%2?bottomIndRow+"rcrcrcrcrcrcrcrcrcrc".substr(1,c):bottomIndRow+"rcrcrcrcrcrcrcrcrcrc".substr(0,c))}
function rearrangeCipher(b){var a,g,c=0;cipherBottomRow=cipherTopRow="";for(g=0;g<Math.floor(cipher.length/b);g+=1){for(a=0;a<Math.floor(b/2);a+=1)cipherTopRow+=cipher[c],cipherTopRow+=cipher[c],c+=1;1===b%2&&(cipherTopRow+=cipher[c],cipherBottomRow+=cipher[c],c+=1);for(a=0;a<Math.floor(b/2);a+=1)cipherBottomRow+=cipher[c],cipherBottomRow+=cipher[c],c+=1}b=cipher.length%b;for(a=0;a<Math.floor(b/2);a+=1)cipherTopRow+=cipher[c],cipherTopRow+=cipher[c],c+=1;1===b%2&&(cipherTopRow+=cipher[c],cipherBottomRow+=
cipher[c],c+=1);for(a=0;a<Math.floor(b/2);a+=1)cipherBottomRow+=cipher[c],cipherBottomRow+=cipher[c],c+=1}function decrypt(b,a){var g;var c=0;plain="";for(g=0;g<cipher.length;g+=1){var e=cipherTopRow[c];e=b.indexOf(e);var d="r"===topIndRow[c]?Math.floor(e/a):e%a;e=cipherBottomRow[c];e=b.indexOf(e);e="r"===bottomIndRow[c]?Math.floor(e/a):e%a;d=d*a+e;plain+=b[d];c+=1}return plain.toLowerCase()}
function solveWithKeyword(){var b;var a=Math.sqrt(alphabet.length);isRunning=!0;if(5===a)var g=getKeyedAlphabet(alphabet,keyword);else{g=getKeyedAlphabet(englishAlph36,keyword);var c=getACAKeyedAlphabet(alphabet,keyword)}var e=minPeriod===maxPeriod&&10<minPeriod?minPeriod:minPeriod+workerNumber;isRunning=!0;for(period=e;period<=maxPeriod;period+=totalWorkers)for(e=0;e<routes.length;e+=1){var d="";createCoordinates(period);rearrangeCipher(period);for(b=0;b<alphabet.length;b+=1)d+=g[routes[e][b]];plain=
decrypt(d,a);b=5===a?getTetraScore(plain):getTetraScore(plain.replace(/[^a-z]/g,""));solutions[numSols-1]<b&&(solutions[numSols-1]=b,solutions.sort(function(m,l){return l-m}),self.postMessage({cmd:"reslt",key:d,score:b,text:plain}));if(6===a){d="";for(b=0;b<alphabet.length;b+=1)d+=c[routes[e][b]];plain=decrypt(d,a);b=getTetraScore(plain.replace(/[^a-z]/g,""));solutions[numSols-1]<b&&(solutions[numSols-1]=b,solutions.sort(function(m,l){return l-m}),self.postMessage({cmd:"reslt",key:d,score:b,text:plain}))}}isRunning=
!1}self.addEventListener("message",function(b){b=b.data;cipher=b.cipher;uInt8Array=b.uInt8Array;totalWorkers=b.totalWorkers;workerNumber=b.workerNumber;numSols=b.numSols;alphabet=b.alphabet;keyword=b.keyword;minPeriod=b.minPeriod;maxPeriod=b.maxPeriod;routes=b.routes;decipherBifid()},!1);