var cipher,uInt8Array,totalWorkers,workerNumber,numSols,keyword1,keyword2,isRunning,keyTrials,gridWd,alphabet,routes,period,topRowIndicator,bottomRowIndicator,cipherTopRow,cipherBottomRow,solutions=[];
function decipherCMBifid(){"function"===typeof importScripts&&(importScripts("../support/decipherLib.js"),importScripts("../support/cryptoPrograms.js"));keyTrials=0;gridWd=5;initSolution();createCoordinates();rearrangeCipher();"undefined"!==typeof keyword1&&"undefined"!==typeof keyword2&&(0<keyword1.length?solveWithKeyword(keyword1,keyword2):solveCMBifid());!1===isRunning&&self.postMessage({cmd:"STOP",msg:""})}
function solveCMBifid(){var a,c,b,d,f,n=[],p=[];var e=[];var g=[],h=[],m=[],q=[],u=[],t;var l=alphabet.length;isRunning=!0;var v=t=!1;e=randomiseAlphabet(l,alphabet).split("");for(a=0;a<e.length;a+=1)n[a]=e[a];e=randomiseAlphabet(l,alphabet).split("");for(a=0;a<e.length;a+=1)p[a]=e[a];for(b=0;1E4>b;b+=1){if(!v){e=randomiseAlphabet(l,alphabet).split("");for(a=0;a<e.length;a+=1)n[a]=e[a];e=randomiseAlphabet(l,alphabet).split("");for(a=0;a<e.length;a+=1)p[a]=e[a]}for(a=0;a<l;a+=1)m[a]=n[a],q[a]=p[a];
var k=decrypt(m,q);e=f=getTetraScore(k);v=!1;for(c=20;0<=c;c-=.1)for(d=0;1E4>d;d+=1){for(a=0;a<m.length;a+=1)g[a]=m[a],h[a]=q[a];0===d%1E3&&(t=!t);k=Math.floor(50*Math.random());switch(k){case 1:case 2:case 8:if(t){for(a=0;a<l;a+=1)u[a]=g[a];for(a=0;a<l;a+=1)g[a]=u[routes[k][a]]}else{for(a=0;a<l;a+=1)u[a]=h[a];for(a=0;a<l;a+=1)h[a]=u[routes[k][a]]}break;case 3:t?swapCols(g):swapCols(h);break;case 4:t?swapRows(g):swapRows(h);break;default:do k=Math.floor(Math.random()*l),a=Math.floor(Math.random()*
l);while(k===a);if(0===d%2){var r=g[k];g[k]=g[a];g[a]=r}else r=h[k],h[k]=h[a],h[a]=r}k=decrypt(g,h);a=getTetraScore(k);r=a-f;if(0<=r)for(f=a,a=0;a<g.length;a+=1)m[a]=g[a],q[a]=h[a];else if(0<c){r=Math.pow(Math.E,r/c);var w=(1E3*Math.random()+1)/1E3;if(r>w)for(f=a,a=0;a<g.length;a+=1)m[a]=g[a],q[a]=h[a]}if(f>e){e=f;v=!0;for(a=0;a<m.length;a+=1)n[a]=m[a],p[a]=q[a];solutions[numSols-1]<e&&(solutions[numSols-1]=e,solutions.sort(function(x,y){return y-x}),self.postMessage({cmd:"reslt",key:n.join("")+"/"+
p.join("").toLowerCase(),score:e,text:k}))}}}isRunning=!1}function swapRows(a){var c;do{var b=Math.floor(Math.random()*gridWd)*gridWd;var d=Math.floor(Math.random()*gridWd)*gridWd}while(b===d);for(c=0;c<gridWd;c+=1){var f=a[b+c];a[b+c]=a[d+c];a[d+c]=f}}function swapCols(a){var c;do{var b=Math.floor(Math.random()*gridWd);var d=Math.floor(Math.random()*gridWd)}while(b===d);for(c=0;c<gridWd;c+=1){var f=a[c*gridWd+b];a[c*gridWd+b]=a[c*gridWd+d];a[c*gridWd+d]=f}}
function decrypt(a,c){var b;var d=cipher.length;var f="";for(b=0;b<d;b+=1){var n="r"===topRowIndicator.substr(b,1)?Math.floor(a.indexOf(cipherTopRow.substr(b,1))/gridWd):a.indexOf(cipherTopRow.substr(b,1))%gridWd;var p="r"===bottomRowIndicator.substr(b,1)?Math.floor(a.indexOf(cipherBottomRow.substr(b,1))/gridWd):a.indexOf(cipherBottomRow.substr(b,1))%gridWd;f+=c[n*gridWd+p]}return f.toLowerCase()}
function rearrangeCipher(){var a,c,b=0;cipherBottomRow=cipherTopRow="";for(c=0;c<Math.floor(cipher.length/period);c+=1){for(a=0;a<Math.floor(period/2);a+=1)cipherTopRow+=cipher[b],cipherTopRow+=cipher[b],b+=1;1===period%2&&(cipherTopRow+=cipher[b],cipherBottomRow+=cipher[b],b+=1);for(a=0;a<Math.floor(period/2);a+=1)cipherBottomRow+=cipher[b],cipherBottomRow+=cipher[b],b+=1}c=cipher.length%period;for(a=0;a<Math.floor(c/2);a+=1)cipherTopRow+=cipher[b],cipherTopRow+=cipher[b],b+=1;1===c%2&&(cipherTopRow+=
cipher[b],cipherBottomRow+=cipher[b],b+=1);for(a=0;a<Math.floor(c/2);a+=1)cipherBottomRow+=cipher[b],cipherBottomRow+=cipher[b],b+=1}
function createCoordinates(){var a;bottomRowIndicator=topRowIndicator="";var c=1===period%2;var b=Math.floor(cipher.length/period);var d=cipher.length%period;for(a=0;a<b;a+=1)topRowIndicator+="rcrcrcrcrcrcrcrcrcrc".substr(0,period);topRowIndicator+="rcrcrcrcrcrcrcrcrcrc".substr(0,d);if(c){for(a=0;a<b;a+=1)bottomRowIndicator+="rcrcrcrcrcrcrcrcrcrc".substr(1,period);bottomRowIndicator=1==d%2?bottomRowIndicator+"rcrcrcrcrcrcrcrcrcrc".substr(1,d):bottomRowIndicator+"rcrcrcrcrcrcrcrcrcrc".substr(0,d)}else bottomRowIndicator=
topRowIndicator}
function solveWithKeyword(a,c){var b,d,f;var n=getKeyedAlphabet(alphabet,a);var p=getKeyedAlphabet(alphabet,c);for(d=0;d<routes.length;d+=1){var e="";for(b=0;b<alphabet.length;b+=1)e+=n[routes[d][b]];for(f=0;f<routes.length;f+=1){var g="";for(b=0;b<alphabet.length;b+=1)g+=p[routes[f][b]];var h=decrypt(e,g);b=getTetraScore(h);solutions[numSols-1]<b&&(solutions[numSols-1]=b,solutions.sort(function(m,q){return q-m}),self.postMessage({cmd:"reslt",key:e+"/"+g.toLowerCase(),score:b,text:h}))}}isRunning=!1}
self.addEventListener("message",function(a){a=a.data;cipher=a.cipher;uInt8Array=a.uInt8Array;totalWorkers=a.totalWorkers;workerNumber=a.workerNumber;numSols=a.numSols;keyword1=a.keyword1;keyword2=a.keyword2;alphabet=a.alphabet;routes=a.routes;period=a.period;decipherCMBifid()},!1);