var plain,period,solutions=[],cipher,horzKey,vertKey,numSols,uInt8Array,workerNumber,totalWorkers,alphabet,isRunning;function decipherDigrafid(){"function"===typeof importScripts&&(importScripts("../support/decipherLib.js"),importScripts("../support/cryptoPrograms.js"));initSolution();alphabet=englishAlph+"#";"undefined"!==typeof horzKey&&"undefined"!==typeof vertKey&&(0<horzKey.length&&0<vertKey.length?solveWithKeyword():solveDigrafid());!1===isRunning&&self.postMessage({cmd:"STOP",msg:""})}
function solveDigrafid(){var b,c,a,e,f,k,n,g=[],d=[],l=[],r=[];var q=alphabet.length;var m=8;var p=0;isRunning=!0;for(f=0;1E4>f;f+=1)if(1===Math.floor(100*Math.random())&&(m=Math.floor(5*Math.random())+8),isRunning){d=0===vertKey.length?randomAlphabet(m).split(""):getKeyedAlphabet(alphabet,vertKey).split("");for(a=0;a<q;a+=1)r[a]=d[a];if(0===f%300)for(g=0===horzKey.length?randomAlphabet(m).split(""):getKeyedAlphabet(alphabet,horzKey).split(""),a=0;a<q;a+=1)l[a]=g[a];for(e=k=n=0;50>e;e+=1){if(0===
vertKey.length)for(b=0;b<m-1;b+=1)for(c=0;c<q;c+=1){for(a=0;a<q;a+=1)d[a]=r[a];do{a=Math.floor(Math.random()*m);var h=Math.floor(Math.random()*m)}while(a===h);var v=d[a];d[a]=d[h];d[h]=v;d=swapKeyedAlphabet(d,m,c,b);plain=decrypt(l.join(""),d.join(""));h=getTetraScore(plain.replace(/[^a-z]/g,""));if(h>n)for(n=h,a=0;a<d.length;a+=1)r[a]=d[a];if(h>p){p=h;for(a=0;a<q;a+=1);for(a=0;a<d.length;a+=1);solutions[numSols-1]<p&&(solutions[numSols-1]=p,solutions.sort(function(t,u){return u-t}),self.postMessage({cmd:"reslt",
key:l.join("")+"/"+d.join("").toLowerCase(),score:h,text:plain}))}}else plain=decrypt(g.join(""),d.join("")),n=getTetraScore(plain.replace(/[^a-z]/g,""));if(0===horzKey.length){for(b=0;b<m-1;b+=1)for(c=0;c<q;c+=1){for(a=0;a<q;a+=1)g[a]=l[a];do a=Math.floor(Math.random()*m),h=Math.floor(Math.random()*m);while(a===h);v=g[a];g[a]=g[h];g[h]=v;g=swapKeyedAlphabet(g,m,c,b);plain=decrypt(g.join(""),r.join(""));h=getTetraScore(plain.replace(/[^a-z]/g,""));if(h>k)for(k=h,a=0;a<g.length;a+=1)l[a]=g[a];if(h>
p){p=h;for(a=0;a<q;a+=1);for(a=0;a<d.length;a+=1);solutions[numSols-1]<p&&(solutions[numSols-1]=p,solutions.sort(function(t,u){return u-t}),self.postMessage({cmd:"reslt",key:g.join("")+"/"+r.join("").toLowerCase(),score:h,text:plain}))}}for(a=0;a<g.length;a+=1)g[a]=l[a];for(a=0;a<d.length;a+=1)d[a]=r[a];for(c=0;500>c;c+=1){g=mixKeyword(g,m);d=mixKeyword(d,m);plain=decrypt(g.join(""),d.join(""));h=getTetraScore(plain.replace(/[^a-z]/g,""));if(h>k){k=h;for(a=0;a<g.length;a+=1)l[a]=g[a];for(a=0;a<d.length;a+=
1)r[a]=d[a]}if(h>p){p=h;for(a=0;a<q;a+=1);for(a=0;a<d.length;a+=1);solutions[numSols-1]<p&&(solutions[numSols-1]=p,solutions.sort(function(t,u){return u-t}),self.postMessage({cmd:"reslt",key:g.join("")+"/"+d.join("").toLowerCase(),score:h,text:plain}))}}}if(k===n)break;k=n}}isRunning=!1}function swapKeyedAlphabet(b,c,a,e){var f=alphabet;b=b.splice(0,c);b[e]=alphabet[a];a=b[0];f=f.replace(b[0],"");for(c=1;c<b.length;c+=1)-1===a.indexOf(b[c])&&(a+=b[c],f=f.replace(b[c],""));return(a+f).split("")}
function mixKeyword(b,c){var a=alphabet;var e=alphabet.length-c;b=b.splice(0,c);do{var f=Math.floor(Math.random()*e)+c;var k=Math.floor(Math.random()*c)}while(0<=b.indexOf(a.charAt(f))||f===k);b[k]=a.charAt(f);for(f=0;f<c;f+=1)a=a.replace(b[f],"");return b.concat(a.split(""))}
function randomAlphabet(b){var c;var a=alphabet.length;var e=alphabet;var f=Math.floor(Math.random()*a);var k=e.charAt(f);e=e.substr(0,f)+e.substr(f+1);for(c=1;c<b;c+=1){f=Math.floor(Math.random()*(a-c));var n=e.charAt(f);k+=n;e=e.substr(0,f)+e.substr(f+1)}return k+e}
function decrypt(b,c){var a,e;var f=cipher.length;var k=Math.floor(period/2);var n="";for(a=0;a<f;a+=period){a+period>f&&(period=f-a,k=Math.floor(period/2));var g=a+period<=f?cipher.substr(a,period):cipher.substr(a);var d=0;var l=[];for(e=0;e<g.length;e+=2)l[d]=b.indexOf(g.charAt(e))%9,l[d+1]=3*Math.floor(b.indexOf(g.charAt(e))/9)+Math.floor(c.indexOf(g.charAt(e+1))/9),l[d+2]=c.indexOf(g.charAt(e+1))%9,d+=3;for(e=0;e<g.length/2;e+=1)d=l[e]+9*Math.floor(l[e+k]/3),n+=b.substr(d,1),d=9*Math.floor(l[e+
k]%3)+l[e+2*k],n+=c.substr(d,1)}return n.toLowerCase()}function solveWithKeyword(){keyedAlph=getKeyedAlphabet(alphabet,horzKey);keyedAlph2=getKeyedAlphabet(alphabet,vertKey);plain=decrypt(keyedAlph,keyedAlph2);var b=getTetraScore(plain.replace(/[^a-z]/g,""));solutions[numSols-1]<b&&(solutions[numSols-1]=b,solutions.sort(function(c,a){return a-c}),self.postMessage({cmd:"reslt",key:horzKey+"/"+vertKey.toLowerCase(),score:b,text:plain}));isRunning=!1}
self.addEventListener("message",function(b){b=b.data;cipher=b.cipher;uInt8Array=b.uInt8Array;totalWorkers=b.totalWorkers;workerNumber=b.workerNumber;numSols=b.numSols;horzKey=b.horzKey;vertKey=b.vertKey;period=b.period;decipherDigrafid()},!1);