var plain,solutions=[],cipher,keyword,numSols,uInt8Array,singleScores,isRunning,matSize,alph,alphSize;function decipherHill(){"function"===typeof importScripts&&(importScripts("../support/decipherLib.js"),importScripts("../support/cryptoPrograms.js"));initSolution();var a;alphSize=alph.length;if(0===keyword.length)if(0===matSize)solve2x2();else for(a=0;2>a;a+=1)solve3x3(a);else solveWithMatrix(keyword);!1===isRunning&&self.postMessage({cmd:"STOP",msg:""})}
function solve2x2(){for(var a,f,c=0,b=[0];b[0]<alphSize;b[0]+=1)for(b[1]=0;b[1]<alphSize;b[1]+=1)for(b[2]=0;b[2]<alphSize;b[2]+=1)for(b[3]=0;b[3]<alphSize;b[3]+=1)if(a=getDeterminant(b),1===a%2&&13!==a)for(a=0;2>a;a+=1)decipher2x2(b,a),f=getTetraScore(plain),f>c&&(c=f,solutions[numSols-1]<f&&(solutions[numSols-1]=f,solutions.sort(function(h,d){return d-h}),self.postMessage({cmd:"reslt",key:b,score:f,text:plain.toLowerCase()})));isRunning=!1}
function decipher2x2(a,f){var c;plain="";var b=chr(ord("a")-1);if(0===f){var h=ord("a");for(c=0;c<cipher.length;c+=2){var d=ord(cipher[c])-ord("A");var e=ord(cipher[c+1])-ord("A");plain+=chr((a[0]*d+a[1]*e)%alphSize+h);plain+=chr((a[2]*d+a[3]*e)%alphSize+h)}}else for(h=ord("a")-1,c=0;c<cipher.length;c+=2){d=ord(cipher[c])-ord("A")+1;26===d&&(d=0);e=ord(cipher[c+1])-ord("A")+1;26===e&&(e=0);var g=chr((a[0]*d+a[1]*e)%alphSize+h);g===chr(ord("a")-1)&&(g="z");plain+=g;g=chr((a[2]*d+a[3]*e)%alphSize+h);
g===b&&(g="z");plain+=g}}
function solve3x3(a){var f,c,b,h=0,d=[],e=[];d.length=200;for(f=0;f<d.length;f+=1)d[f]=[2],d[f][0]=0;var g=0;for(e[0]=0;e[0]<alphSize;e[0]+=1)for(e[1]=0;e[1]<alphSize;e[1]+=1)for(e[2]=0;e[2]<alphSize;e[2]+=1)decipherSingleRow(e,a),g=getSingleSingleScore(plain),f=e[0]+(e[1]<<5)+(e[2]<<10),g>d[d.length-1][0]&&(d[d.length-1][0]=g,d[d.length-1][1]=f,d.sort(sortFunction));for(f=0;f<d.length;f+=1)for(e[0]=d[f][1]&31,e[1]=d[f][1]>>5&31,e[2]=d[f][1]>>10&31,c=0;c<d.length;c+=1)for(e[3]=d[c][1]&31,e[4]=d[c][1]>>
5&31,e[5]=d[c][1]>>10&31,b=0;b<d.length;b+=1)e[6]=d[b][1]&31,e[7]=d[b][1]>>5&31,e[8]=d[b][1]>>10&31,g=getDeterminant(e),1===g%2&&13!==g&&(decipher3x3(e,a),g=getTetraScore(plain),g>h&&(h=g,solutions[numSols-1]<g&&(solutions[numSols-1]=g,solutions.sort(function(k,l){return l-k}),self.postMessage({cmd:"reslt",key:e,score:g,text:plain.toLowerCase()}))));isRunning=!1}
function solveWithMatrix(a){var f=0,c=[];c=a.split(/[ ,]+/);if(4===c.length){var b=getDeterminant(c);if(1===b%2&&13!==b)for(a=0;2>a;a+=1)decipher2x2(c,a),b=getTetraScore(plain),b>f&&(f=b,solutions[numSols-1]<b&&(solutions[numSols-1]=b,solutions.sort(function(h,d){return d-h}),self.postMessage({cmd:"reslt",key:c,score:b,text:plain.toLowerCase()})))}else for(a=b=0;2>a;a+=1)b=getDeterminant(c),1===b%2&&13!==b&&(decipher3x3(c,a),b=getTetraScore(plain),b>f&&(f=b,solutions[numSols-1]<b&&(solutions[numSols-
1]=b,solutions.sort(function(h,d){return d-h}),self.postMessage({cmd:"reslt",key:c,score:b,text:plain.toLowerCase()}))));isRunning=!1}
function decipher3x3(a,f){var c;plain="";if(0===f){var b=ord("a");for(c=0;c<cipher.length;c+=3){var h=ord(cipher[c])-ord("A");var d=ord(cipher[c+1])-ord("A");var e=ord(cipher[c+2])-ord("A");plain+=chr((a[0]*h+a[1]*d+a[2]*e)%alphSize+b);plain+=chr((a[3]*h+a[4]*d+a[5]*e)%alphSize+b);plain+=chr((a[6]*h+a[7]*d+a[8]*e)%alphSize+b)}}else for(b=ord("a")-1,c=0;c<cipher.length;c+=3){h=(ord(cipher[c])-ord("A")+1)%alphSize;d=(ord(cipher[c+1])-ord("A")+1)%alphSize;e=(ord(cipher[c+2])-ord("A")+1)%alphSize;var g=
chr((a[0]*h+a[1]*d+a[2]*e)%alphSize+b);g===chr(b)&&(g="z");plain+=g;g=chr((a[3]*h+a[4]*d+a[5]*e)%alphSize+b);g===chr(b)&&(g="z");plain+=g;g=chr((a[6]*h+a[7]*d+a[8]*e)%alphSize+b);g===chr(b)&&(g="z");plain+=g}}function getDeterminant(a){if(0===matSize)var f=a[0]*a[3]-a[1]*a[2];else f=a[0]*a[4]*a[8]+a[1]*a[5]*a[6]+a[2]*a[3]*a[7],f-=a[2]*a[4]*a[6]+a[0]*a[5]*a[7]+a[1]*a[3]*a[8];return getModuloRemainder(f,alphSize)}function getModuloRemainder(a,f){return(a%f+f)%f}
function decipherSingleRow(a,f){var c;plain="";var b=chr(ord("a")-1);if(0===f){var h=ord("a");for(c=0;c<cipher.length;c+=3){var d=ord(cipher[c])-ord("A");var e=ord(cipher[c+1])-ord("A");var g=ord(cipher[c+2])-ord("A");plain+=chr((a[0]*d+a[1]*e+a[2]*g)%alphSize+h)}}else for(h=ord("a")-1,c=0;c<cipher.length;c+=3)d=ord(cipher[c])-ord("A")+1,26===d&&(d=0),e=ord(cipher[c+1])-ord("A")+1,26===e&&(e=0),g=ord(cipher[c+2])-ord("A")+1,26===g&&(g=0),d=chr((a[0]*d+a[1]*e+a[2]*g)%alphSize+h),d===b&&(d="z"),plain+=
d}self.addEventListener("message",function(a){a=a.data;cipher=a.cipher;uInt8Array=a.uInt8Array;numSols=a.numSols;matSize=a.matSize;alph=a.alph;keyword=a.keyword;singleScores=a.singleScores;decipherHill()},!1);