var solutions=[],cipher,cipherNum,keyword,numKeyword,row1,row2,numSols,uInt8Array,alphabet,isRunning;
function decipherMonomeDin(){"function"===typeof importScripts&&(importScripts("../support/decipherLib.js"),importScripts("../support/cryptoPrograms.js"));initSolution();alphabet=englishAlph.replace("J","");alphabet=alphabet.replace("Z","");cipherNum=cipher.split("");"undefined"!==typeof keyword&&(0<keyword.length?solveWithKeyword():solveMonomeDin());!1===isRunning&&self.postMessage({cmd:"STOP",msg:""})}
function solveMonomeDin(){var a,b,d,c,f=[];var g=[];var e=[],k=[];var n=alphabet.length;var m=Number.MAX_SAFE_INTEGER;k=getRowNumbers();isRunning=!0;for(b=0;b<k.length;b+=1)for(row1=Number(k[b].charAt(0)),row2=Number(k[b].charAt(1)),numKeyword="0123456789".replace(row1,""),numKeyword=numKeyword.replace(row2,""),d=0;700>d;d+=1)if(isRunning){g=randomiseAlphabet(n,alphabet).split("");for(a=0;a<g.length;a+=1)e[a]=g[a],f[a]=g[a];var h=decrypt(e.join(""),numKeyword);var p=getTetraScore(h);if(solutions[numSols-
1]<p&&h.length<=m){m=h.length;solutions[numSols-1]=p;solutions.sort(function(q,r){return r-q});var l=getOrderedKeys(e);self.postMessage({cmd:"reslt",key:l,score:p,text:h})}for(c=15;2<c;--c){g=0;do{for(a=0;a<f.length;a+=1)e[a]=f[a];a=Math.floor(Math.random()*n);l=Math.floor(Math.random()*n);h=e[a];e[a]=e[l];e[l]=h;h=decrypt(e.join(""),numKeyword);a=getTetraScore(h);solutions[numSols-1]<a&&h.length<=m&&(m=h.length,solutions[numSols-1]=a,solutions.sort(function(q,r){return r-q}),l=getOrderedKeys(e),
self.postMessage({cmd:"reslt",key:l,score:a,text:h}));h=a-p;l=0;if(0<h)l=1;else{h=Math.pow(Math.E,h/c);var t=(1E3*Math.random()+1)/1E3;h>t&&(l=1)}1===l&&(f=e.slice(),p=a);g+=1}while(200>g&&isRunning)}}isRunning=!1}
function getRowNumbers(){var a,b,d,c=[],f=[],g=[];for(a=d=0;10>a;a+=1)if(g[a]=0,a!==cipher.slice(-1))for(b=a+1;10>b;b+=1)b!==cipher.slice(-1)&&(c[d]=a.toString()+b.toString(),d+=1);for(a=d=0;a<cipher.length;a+=1){g[cipher.charAt(a)]+=1;var e=a.toString();0<=cipher.indexOf(e+e)&&0<=c.indexOf(e+e)&&(c.splice(c.indexOf(e+e),1),f[d]=a,d+=1)}if(0<f.length)for(a=0;a<f.length;a+=1)for(e=f[a],b=0;b<c.length;b+=1)0<=c.indexOf(e)&&c.splice(b,1);for(a=0;a<cipher.length;a+=1)e=cipher.charAt(a),e===cipher.charAt(a+
2)&&(0<=c.indexOf(e+cipher.charAt(a+2))&&c.splice(a,1),0<=c.indexOf(cipher.charAt(a+2)+e)&&c.splice(a,1));for(a=0;a<cipher.length;a+=1)e=cipher.charAt(a)+cipher.charAt(a+1),0<=c.indexOf(e)&&c.splice(c.indexOf(e),1),e=cipher.charAt(a+1)+cipher.charAt(a),0<=c.indexOf(e)&&c.splice(c.indexOf(e),1);return c=sort(c,g)}
function sort(a,b){var d,c,f=[];for(d=0;d<a.length;d+=1)f[d]=b[Number(a[d].substr(0,1))]+b[Number(a[d].substr(1,1))];for(d=1;d<f.length;d+=1)for(c=0;c<f.length-1;c+=1)if(f[c+1]>f[c]){var g=f[c];f[c]=f[c+1];f[c+1]=g;g=a[c];a[c]=a[c+1];a[c+1]=g}return a}
function getOrderedKeys(a){var b,d;var c=ord("A");var f=ord("Z"),g=[],e=[];var k=d=0;for(b=8;16>b;b+=1)d+=a[b],k+=a[b+8];for(b=0;b<a.length;b+=1)e[b]="";if(d>k){var n=a.join("").substr(a.length-16,8);var m=row2.toString()+row1.toString()+"/"}else n=a.join("").substr(a.length-8),m=row1.toString()+row2.toString()+"/";var h=0;for(b=c;b<=f;b+=1)c=chr(b),c=n.indexOf(c),0<=c&&(m+=numKeyword.charAt(c),g[c]=h,h+=1);for(b=0;b<g.length;b+=1)e[g[b]]=a[b],d>k?(e[g[b]+8]=a[b+16],e[g[b]+16]=a[b+8]):(e[g[b]+8]=
a[b+8],e[g[b]+16]=a[b+16]);return e.join("")+"("+m+")"}function decrypt(a,b){var d;var c="";for(d=0;d<cipherNum.length;d+=1){switch(Number(cipherNum[d])){case row1:var f=b.indexOf(Number(cipherNum[d+1]))+8;d+=1;break;case row2:f=b.indexOf(Number(cipherNum[d+1]))+16;d+=1;break;default:f=b.indexOf(Number(cipherNum[d]))}c+=a.charAt(f)}return c.toLowerCase()}
function solveWithKeyword(){var a,b;var d=ord("A");var c=ord("Z");var f=[];if(""===numKeyword){for(a=0;d<=c;d+=1){var g=chr(d);for(b=keyword.indexOf(g);0<=b&&a<keyword.length&&10>a;)f[b]=a,a+=1,b=keyword.indexOf(g,b+1)}numKeyword=f.join("");for(d=0;10>d;d+=1)-1===numKeyword.indexOf(d)&&(numKeyword+=d.toString())}numKeyword=numKeyword.replace(row1,"");numKeyword=numKeyword.replace(row2,"");keyword=keyword.replace("J","I");keyword=keyword.replace("Z","Y");c=getKeyedAlphabet(alphabet,keyword);f=decrypt(c,
numKeyword);a=getTetraScore(f);solutions[numSols-1]<a&&(solutions[numSols-1]=a,solutions.sort(function(e,k){return k-e}),self.postMessage({cmd:"reslt",key:c+"("+row1.toString()+row2.toString()+"/"+numKeyword+")",score:a,text:f}));isRunning=!1}self.addEventListener("message",function(a){a=a.data;cipher=a.cipher;uInt8Array=a.uInt8Array;numSols=a.numSols;keyword=a.keyword;numKeyword=a.numKeyword;row1=a.row1;row2=a.row2;decipherMonomeDin()},!1);