var cipher,numSols,uInt8Array,workerNumber,totalWorkers,alphabet,routes,minPeriod,maxPeriod,keyword,hdrKeyword,isRunning,solutions=[],cipherNum=[],numberRange=[],bestMatch=[];
function decipherNihilSubs(){"function"===typeof importScripts&&(importScripts("../support/decipherLib.js"),importScripts("../support/cryptoPrograms.js"));initSolution();readCipherPairs();"undefined"!==typeof keyword&&(0<keyword.length&&0<hdrKeyword.length?solveWithKeyword():solveNihilSubs());!1===isRunning&&self.postMessage({cmd:"STOP",msg:""})}
function readCipherPairs(){var b,a=0;for(b=0;b<cipher.length;b+=2)cipherNum[a]=10*parseInt(cipher.charAt(b))+parseInt(cipher.charAt(b+1)),10>=cipherNum[a]&&(cipherNum[a]+=100),a+=1}function solveNihilSubs(){var b;for(b=0;15>b;b+=1)numberRange[b]=[],numberRange[b][0]=0,numberRange[b][1]=0;isRunning=!0;for(b=minPeriod;b<=maxPeriod;b+=1)keyIsValid(b)&&(parseKeyword(b),findAllKeys(b));0<bestMatch.length&&(bestMatch.sort(sortFunctionAsc),decipherMonoAlph());isRunning=!1}
function keyIsValid(b){var a=!0;var e=cipherNum.length-b;var d=0;do{var g=Math.floor(cipherNum[d]/10);var c=cipherNum[d]%10;0===c&&(c=10,--g);var f=Math.floor(cipherNum[d+b]/10);var h=cipherNum[d+b]%10;0===h&&(h=10,--f);4<Math.abs(c-h)&&(a=!1);4<Math.abs(g-f)&&(a=!1);d+=1}while(!0===a&&d<e);return a}
function parseKeyword(b){var a,e;for(e=0;e<b;e+=1){var d=10;var g=1;var c=10;var f=1;for(a=e;a<cipherNum.length;a+=b){var h=Math.floor(cipherNum[a]/10);0===h&&(h=10);var k=cipherNum[a]%10;0===k&&(k=10,--h);h<d&&(d=h);h>g&&(g=h);k<c&&(c=k);k>f&&(f=k)}a=g-5;1>a&&(a=1);f-=5;1>f&&(f=1);--d;5<d&&(d=5);--c;5<c&&(c=5);numberRange[e][0]=10*a+f;numberRange[e][1]=10*d+c}}
function findAllKeys(b){var a=[];for(a[14]=numberRange[14][0];a[14]<=numberRange[14][1];){if(a[14]%10>=numberRange[14][0]%10&&a[14]%10<=numberRange[14][1]%10)for(a[13]=numberRange[13][0];a[13]<=numberRange[13][1];){if(a[13]%10>=numberRange[13][0]%10&&a[13]%10<=numberRange[13][1]%10)for(a[12]=numberRange[12][0];a[12]<=numberRange[12][1];){if(a[12]%10>=numberRange[12][0]%10&&a[12]%10<=numberRange[12][1]%10)for(a[11]=numberRange[11][0];a[11]<=numberRange[11][1];){if(a[11]%10>=numberRange[11][0]%10&&
a[11]%10<=numberRange[11][1]%10)for(a[10]=numberRange[10][0];a[10]<=numberRange[10][1];){if(a[10]%10>=numberRange[10][0]%10&&a[10]%10<=numberRange[10][1]%10)for(a[9]=numberRange[9][0];a[9]<=numberRange[9][1];){if(a[9]%10>=numberRange[9][0]%10&&a[9]%10<=numberRange[9][1]%10){a[8]=numberRange[8][0];if(!isRunning)return;for(;a[8]<=numberRange[8][1];){if(a[8]%10>=numberRange[8][0]%10&&a[8]%10<=numberRange[8][1]%10)for(a[7]=numberRange[7][0];a[7]<=numberRange[7][1];){if(a[7]%10>=numberRange[7][0]%10&&
a[7]%10<=numberRange[7][1]%10)for(a[6]=numberRange[6][0];a[6]<=numberRange[6][1];){if(a[6]%10>=numberRange[6][0]%10&&a[6]%10<=numberRange[6][1]%10)for(a[5]=numberRange[5][0];a[5]<=numberRange[5][1];){if(a[5]%10>=numberRange[5][0]%10&&a[5]%10<=numberRange[5][1]%10)for(a[4]=numberRange[4][0];a[4]<=numberRange[4][1];){if(a[4]%10>=numberRange[4][0]%10&&a[4]%10<=numberRange[4][1]%10)for(a[3]=numberRange[3][0];a[3]<=numberRange[3][1];){if(a[3]%10>=numberRange[3][0]%10&&a[3]%10<=numberRange[3][1]%10)for(a[2]=
numberRange[2][0];a[2]<=numberRange[2][1];){if(a[2]%10>=numberRange[2][0]%10&&a[2]%10<=numberRange[2][1]%10)for(a[1]=numberRange[1][0];a[1]<=numberRange[1][1];){if(a[1]%10>=numberRange[1][0]%10&&a[1]%10<=numberRange[1][1]%10)for(a[0]=numberRange[0][0];a[0]<=numberRange[0][1];){if(a[0]%10>=numberRange[0][0]%10&&a[0]%10<=numberRange[0][1]%10){var e=decrypt(a,alphabet,b);var d=Math.floor(1E4*Math.abs(calculateIOC(e)-.067));var g=a[0];for(e=1;e<b;e+=1)g+=","+a[e];bestMatch.push([d,g])}a[0]+=1}a[1]+=1}a[2]+=
1}a[3]+=1}a[4]+=1}a[5]+=1}a[6]+=1}a[7]+=1}a[8]+=1}}a[9]+=1}a[10]+=1}a[11]+=1}a[12]+=1}a[13]+=1}a[14]+=1}}function calculateIOC(b){var a;var e=0;var d,g=ord("A"),c=[];b=b.toUpperCase();for(a=d=0;26>a;a+=1)c[a]=0;for(a=0;a<b.length;a+=1)c[ord(b.charAt(a))-g]+=1,e+=1;if(0<e){for(a=b=e=0;26>a;a+=1)0<c[a]&&(e+=c[a]*(c[a]-1),b+=c[a]);1<b&&(d=e/(b*(b-1)))}return d}function sortFunctionAsc(b,a){return b[0]===a[0]?0:b[0]<a[0]?-1:1}
function decipherMonoAlph(){var b,a,e,d=[];var g=[];var c=[],f=[];var h=alphabet.length;for(e=workerNumber;e<bestMatch.length;e+=totalWorkers){var k=bestMatch[e][1];f=k.split(",");var q=f.length;for(k=0;500>k;k+=1)if(isRunning){g=randomiseAlphabet(h,alphabet).split("");for(b=0;b<g.length;b+=1)c[b]=g[b],d[b]=g[b];var m=decrypt(f,c.join(""),q);if(m.length===cipherNum.length){var p=getTetraScore(m);if(solutions[numSols-1]<p){hdrKeyword="";for(b=0;b<q;b+=1){var l=5*(Math.floor(f[b]/10)-1)+f[b]%10-1;hdrKeyword+=
c[l]}solutions[numSols-1]=p;solutions.sort(function(r,t){return t-r});self.postMessage({cmd:"reslt",key:c.join("")+"/"+hdrKeyword,score:p,text:m})}for(a=15;2<a;--a){g=0;do{for(b=0;b<d.length;b+=1)c[b]=d[b];l=Math.floor(Math.random()*h);var n=Math.floor(Math.random()*h);b=c[l];c[l]=c[n];c[n]=b;m=decrypt(f,c.join(""),q);n=getTetraScore(m);if(solutions[numSols-1]<n){hdrKeyword="";for(b=0;b<q;b+=1)l=5*(Math.floor(f[b]/10)-1)+f[b]%10-1,hdrKeyword+=c[l];solutions[numSols-1]=n;solutions.sort(function(r,
t){return t-r});self.postMessage({cmd:"reslt",key:c.join("")+"/"+hdrKeyword,score:n,text:m})}b=n-p;l=0;0<b?l=1:(b=Math.pow(Math.E,b/a),m=(1E3*Math.random()+1)/1E3,b>m&&(l=1));1===l&&(d=c.slice(),p=n);g+=1}while(1E3>g&&isRunning)}}}}}function decrypt(b,a,e){var d;var g="";var c=0;var f=a.length;for(d=0;d<cipherNum.length;d+=1){var h=cipherNum[d]-b[c];9<h&&(h=5*(Math.floor(h/10)-1)+h%10-1,0<=h&&h<f&&(g+=a.charAt(h)));c+=1;c===e&&(c=0)}return g.toLowerCase()}
function solveWithKeyword(){var b,a,e=[];var d=getKeyedAlphabet(alphabet,keyword);var g=hdrKeyword.length;for(a=0;a<routes.length;a+=1){var c="";for(b=0;b<alphabet.length;b+=1)c+=d[routes[a][b]];for(b=0;b<g;b+=1){var f=c.indexOf(hdrKeyword.charAt(b));e[b]=10*(Math.floor(f/5)+1)+f%5+1}f=decrypt(e,c,g);f.length===cipherNum.length&&(b=getTetraScore(f),solutions[numSols-1]<b&&(solutions[numSols-1]=b,solutions.sort(function(h,k){return k-h}),self.postMessage({cmd:"reslt",key:c+"/"+hdrKeyword,score:b,text:f})))}isRunning=
!1}self.addEventListener("message",function(b){b=b.data;cipher=b.cipher;uInt8Array=b.uInt8Array;totalWorkers=b.totalWorkers;workerNumber=b.workerNumber;numSols=b.numSols;alphabet=b.alphabet;keyword=b.keyword;hdrKeyword=b.hdrKeyword;routes=b.routes;minPeriod=b.minPeriod;maxPeriod=b.maxPeriod;decipherNihilSubs()},!1);