var solutions=[],cipher,cipherNum,keyword,numKeyword,row1,row2,numSols,uInt8Array,workerNumber,totalWorkers,alphabet,isRunning;function decipherStrad(){"function"===typeof importScripts&&(importScripts("../support/decipherLib.js"),importScripts("../support/cryptoPrograms.js"));initSolution();alphabet=englishAlph;cipherNum=cipher.split("");"undefined"!==typeof keyword&&(0<keyword.length?solveWithKeyword():solveStrad());!1===isRunning&&self.postMessage({cmd:"STOP",msg:""})}
function solveStrad(){var a,d,c,e=[];var b=[];var f=[],m=[];var k=Number.MAX_SAFE_INTEGER;numKeyword="0123456789";m=getRowNumbers();isRunning=!0;for(d=workerNumber;d<m.length;d+=totalWorkers){row1=Number(m[d].charAt(0));row2=Number(m[d].charAt(1));var p=alphabet.length;for(c=0;1E3>c;c+=1)if(isRunning){b=randomiseAlphabet(p,englishAlph).split("");var l=numKeyword.indexOf(row1);var n=numKeyword.indexOf(row2);l<n?(b.splice(l,0," "),b.splice(n,0," ")):(b.splice(n,0," "),b.splice(l,0," "));b.push(" ");
b.push(" ");for(a=0;a<b.length;a+=1)f[a]=b[a],e[a]=b[a];var g=decrypt(f.join(""),numKeyword);l=getTetraScore(g.replace(/[^a-z]/g,""));if(solutions[numSols-1]<l&&g.length<=k){k=g.length;solutions[numSols-1]=l;solutions.sort(function(q,r){return r-q});var h=getOrderedKeys(f);self.postMessage({cmd:"reslt",key:h,score:l,text:g})}for(n=15;2<n;--n){b=0;do{for(a=0;a<e.length;a+=1)f[a]=e[a];do a=Math.floor(Math.random()*p),h=Math.floor(Math.random()*p);while(" "===f[a]||" "===f[h]||a===h);g=f[a];f[a]=f[h];
f[h]=g;g=decrypt(f.join(""),numKeyword);a=getTetraScore(g.replace(/[^a-z]/g,""));solutions[numSols-1]<a&&g.length<=k&&(k=g.length,solutions[numSols-1]=a,solutions.sort(function(q,r){return r-q}),h=getOrderedKeys(f),self.postMessage({cmd:"reslt",key:h,score:a,text:g}));g=a-l;h=0;if(0<g)h=1;else{g=Math.pow(Math.E,g/n);var t=(1E3*Math.random()+1)/1E3;g>t&&(h=1)}1===h&&(e=f.slice(),l=a);b+=1}while(200>b&&isRunning)}}}isRunning=!1}
function getRowNumbers(){var a,d,c,e=[],b=[];for(a=c=0;10>a;a+=1)for(b[a]=0,d=a+1;10>d;d+=1)e[c]=a.toString()+d.toString(),c+=1;for(a=0;a<cipher.length;a+=1)b[cipher.charAt(a)]+=1;return e=sort(e,b)}function sort(a,d){var c,e,b=[];for(c=0;c<a.length;c+=1)b[c]=d[Number(a[c].substr(0,1))]+d[Number(a[c].substr(1,1))];for(c=1;c<b.length;c+=1)for(e=0;e<b.length-1;e+=1)if(b[e+1]>b[e]){var f=b[e];b[e]=b[e+1];b[e+1]=f;f=a[e];a[e]=a[e+1];a[e+1]=f}return a}
function getOrderedKeys(a){var d;var c=ord("A");var e=ord("Z"),b=[],f=[];for(d=0;d<a.length;d+=1)f[d]="";var m=a.join("").substr(10,10);var k=0;var p=row1.toString()+row2.toString()+"/";for(d=c;d<=e;d+=1)c=chr(d),c=m.indexOf(c),p+=numKeyword.charAt(c),0<=c&&(b[c]=k,k+=1);for(d=0;d<b.length;d+=1)f[b[d]]=a[d],f[b[d]+10]=a[d+10],f[b[d]+20]=a[d+20];return f.join("")+"("+p+")"}
function decrypt(a,d){var c;var e="";for(c=0;c<cipherNum.length;c+=1){switch(Number(cipherNum[c])){case row1:var b=d.indexOf(Number(cipherNum[c+1]))+10;c+=1;break;case row2:b=d.indexOf(Number(cipherNum[c+1]))+20;c+=1;break;default:b=d.indexOf(Number(cipherNum[c]))}e+=a.charAt(b)}return e.toLowerCase()}
function solveWithKeyword(){var a,d;var c=ord("A");var e=ord("Z");var b=[];if(""===numKeyword){for(a=0;c<=e;c+=1){var f=chr(c);for(d=keyword.indexOf(f);0<=d&&a<keyword.length&&10>a;)b[d]=a,a+=1,d=keyword.indexOf(f,d+1)}numKeyword=b.join("");for(c=0;10>c;c+=1)-1===numKeyword.indexOf(c)&&(numKeyword+=c.toString())}e=numKeyword.indexOf(row1);b=numKeyword.indexOf(row2);a=getKeyedAlphabet(alphabet,keyword);e<b?(a=a.slice(0,e)+" "+a.slice(e),a=a.slice(0,b)+" "+a.slice(b)):(a=a.slice(0,b)+" "+a.slice(b),
a=a.slice(0,e)+" "+a.slice(e));a+="  ";b=decrypt(a,numKeyword);e=getTetraScore(b.replace(/[^a-z]/g,""));solutions[numSols-1]<e&&(solutions[numSols-1]=e,solutions.sort(function(m,k){return k-m}),self.postMessage({cmd:"reslt",key:a+"("+row1.toString()+row2.toString()+"/"+numKeyword+")",score:e,text:b}));isRunning=!1}
self.addEventListener("message",function(a){a=a.data;cipher=a.cipher;uInt8Array=a.uInt8Array;totalWorkers=a.totalWorkers;workerNumber=a.workerNumber;numSols=a.numSols;keyword=a.keyword;numKeyword=a.numKeyword;row1=a.row1;row2=a.row2;decipherStrad()},!1);